/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanLogsRouteImport } from './routes/scan-logs'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QrScannerRouteImport } from './routes/qr-scanner'
import { Route as QrGeneratorRouteImport } from './routes/qr-generator'
import { Route as PublicDocumentsRouteImport } from './routes/public-documents'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MovementsRouteImport } from './routes/movements'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicViewIdRouteImport } from './routes/public-view_.$id'
import { Route as DocumentsDocIdRouteImport } from './routes/documents_.$docId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanLogsRoute = ScanLogsRouteImport.update({
  id: '/scan-logs',
  path: '/scan-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QrScannerRoute = QrScannerRouteImport.update({
  id: '/qr-scanner',
  path: '/qr-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const QrGeneratorRoute = QrGeneratorRouteImport.update({
  id: '/qr-generator',
  path: '/qr-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDocumentsRoute = PublicDocumentsRouteImport.update({
  id: '/public-documents',
  path: '/public-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsRoute = MovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicViewIdRoute = PublicViewIdRouteImport.update({
  id: '/public-view_/$id',
  path: '/public-view/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocIdRoute = DocumentsDocIdRouteImport.update({
  id: '/documents_/$docId',
  path: '/documents/$docId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/movements': typeof MovementsRoute
  '/profile': typeof ProfileRoute
  '/public-documents': typeof PublicDocumentsRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/qr-scanner': typeof QrScannerRoute
  '/register': typeof RegisterRoute
  '/scan-logs': typeof ScanLogsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRoute
  '/users': typeof UsersRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/public-view/$id': typeof PublicViewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/movements': typeof MovementsRoute
  '/profile': typeof ProfileRoute
  '/public-documents': typeof PublicDocumentsRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/qr-scanner': typeof QrScannerRoute
  '/register': typeof RegisterRoute
  '/scan-logs': typeof ScanLogsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRoute
  '/users': typeof UsersRoute
  '/documents/$docId': typeof DocumentsDocIdRoute
  '/public-view/$id': typeof PublicViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/movements': typeof MovementsRoute
  '/profile': typeof ProfileRoute
  '/public-documents': typeof PublicDocumentsRoute
  '/qr-generator': typeof QrGeneratorRoute
  '/qr-scanner': typeof QrScannerRoute
  '/register': typeof RegisterRoute
  '/scan-logs': typeof ScanLogsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRoute
  '/users': typeof UsersRoute
  '/documents_/$docId': typeof DocumentsDocIdRoute
  '/public-view_/$id': typeof PublicViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/logout'
    | '/movements'
    | '/profile'
    | '/public-documents'
    | '/qr-generator'
    | '/qr-scanner'
    | '/register'
    | '/scan-logs'
    | '/settings'
    | '/signup'
    | '/track'
    | '/users'
    | '/documents/$docId'
    | '/public-view/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/logout'
    | '/movements'
    | '/profile'
    | '/public-documents'
    | '/qr-generator'
    | '/qr-scanner'
    | '/register'
    | '/scan-logs'
    | '/settings'
    | '/signup'
    | '/track'
    | '/users'
    | '/documents/$docId'
    | '/public-view/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/logout'
    | '/movements'
    | '/profile'
    | '/public-documents'
    | '/qr-generator'
    | '/qr-scanner'
    | '/register'
    | '/scan-logs'
    | '/settings'
    | '/signup'
    | '/track'
    | '/users'
    | '/documents_/$docId'
    | '/public-view_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  MovementsRoute: typeof MovementsRoute
  ProfileRoute: typeof ProfileRoute
  PublicDocumentsRoute: typeof PublicDocumentsRoute
  QrGeneratorRoute: typeof QrGeneratorRoute
  QrScannerRoute: typeof QrScannerRoute
  RegisterRoute: typeof RegisterRoute
  ScanLogsRoute: typeof ScanLogsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TrackRoute: typeof TrackRoute
  UsersRoute: typeof UsersRoute
  DocumentsDocIdRoute: typeof DocumentsDocIdRoute
  PublicViewIdRoute: typeof PublicViewIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-logs': {
      id: '/scan-logs'
      path: '/scan-logs'
      fullPath: '/scan-logs'
      preLoaderRoute: typeof ScanLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-scanner': {
      id: '/qr-scanner'
      path: '/qr-scanner'
      fullPath: '/qr-scanner'
      preLoaderRoute: typeof QrScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr-generator': {
      id: '/qr-generator'
      path: '/qr-generator'
      fullPath: '/qr-generator'
      preLoaderRoute: typeof QrGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-documents': {
      id: '/public-documents'
      path: '/public-documents'
      fullPath: '/public-documents'
      preLoaderRoute: typeof PublicDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements': {
      id: '/movements'
      path: '/movements'
      fullPath: '/movements'
      preLoaderRoute: typeof MovementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-view_/$id': {
      id: '/public-view_/$id'
      path: '/public-view/$id'
      fullPath: '/public-view/$id'
      preLoaderRoute: typeof PublicViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents_/$docId': {
      id: '/documents_/$docId'
      path: '/documents/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof DocumentsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  MovementsRoute: MovementsRoute,
  ProfileRoute: ProfileRoute,
  PublicDocumentsRoute: PublicDocumentsRoute,
  QrGeneratorRoute: QrGeneratorRoute,
  QrScannerRoute: QrScannerRoute,
  RegisterRoute: RegisterRoute,
  ScanLogsRoute: ScanLogsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TrackRoute: TrackRoute,
  UsersRoute: UsersRoute,
  DocumentsDocIdRoute: DocumentsDocIdRoute,
  PublicViewIdRoute: PublicViewIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
